### ISSUE TITLE
GoLand IDE Fatal Errors

### ISSUE THREAD

**Issue by RustamKuramshin** [ermadan/kafkalytic#2]
После установки плагина в GolLand и открытия интерфейса брокера возникает fatal error со следующим стэктрейсом:
**java.lang.ClassCastException: class javax.swing.tree.DefaultMutableTreeNode cannot be cast to class org.kafkalytic.plugin.KafkaNode (javax.swing.tree.DefaultMutableTreeNode is in module java.desktop of loader 'bootstrap'; org.kafkalytic.plugin.KafkaNode is in unnamed module of loader com.intellij.ide.plugins.cl.PluginClassLoader @6948327b)
	at org.kafkalytic.plugin.MainWindow$2$1.invoke(MainWindow.kt:62)
	at org.kafkalytic.plugin.MainWindow$2$1.invoke(MainWindow.kt:31)
	at org.kafkalytic.plugin.MainWindow$background$1.run(MainWindow.kt:374)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)**

**Comment by RustamKuramshin** [comment]
Сведения о версии GoLand:
GoLand 2019.2.2
Build #GO-192.6603.35, built on September 11, 2019
Licensed to GoLand Evaluator
Expiration date: September 27, 2019
Runtime version: 11.0.3+12-b304.56 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-64-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: CMD Support, Mongo 2.0, com.intellij.apacheConfig, com.intellij.ideolog, com.jetbrains.php.framework, W3Validators, ideanginx9, jms-messenger, mobi.hsz.idea.gitignore, org.ermadan.kafkalytic, org.jetbrains.action-tracker, NodeJS, com.intellij.plugins.html.instantEditing, com.jetbrains.lang.ejs, com.intellij.lang.puppet, training

**Comment by ermadan** [comment]
hi,
can you pls check alpha version and see if it fixes the issue?
https://plugins.jetbrains.com/plugin/11946-kafkalytic/update/70122

**Comment by RustamKuramshin** [comment]
Прошлая ошибка устранена в версии 0.7. 
Но возникает другая при попытке получения сообщений из топика.
org.apache.kafka.common.KafkaException: Failed to construct kafka consumer
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:799)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:650)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:630)
	at org.kafkalytic.plugin.Consumer.run(Consumer.kt:31)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:894)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:408)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: org.apache.kafka.common.config.ConfigException: No resolvable bootstrap urls given in bootstrap.servers
	at org.apache.kafka.clients.ClientUtils.parseAndValidateAddresses(ClientUtils.java:66)
	at org.apache.kafka.clients.consumer.KafkaConsumer.<init>(KafkaConsumer.java:709)
	... 16 more

**Comment by RustamKuramshin** [comment]
GoLand 2019.2.3
Build #GO-192.6817.25, built on October 2, 2019
Licensed to Рустам Курамшин
Subscription is active until October 26, 2019
Runtime version: 11.0.4+10-b304.69 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux 4.15.0-65-generic
GC: ParNew, ConcurrentMarkSweep
Memory: 2014M
Cores: 4
Registry: run.processes.with.pty=TRUE, ide.completion.variant.limit=500, suggest.all.run.configurations.from.context=true
Non-Bundled Plugins: CMD Support, Mongo 2.0, com.intellij.apacheConfig, com.intellij.ideolog, com.intellij.properties, com.intellij.tasks, com.jetbrains.php.framework, W3Validators, ideanginx9, jms-messenger, mobi.hsz.idea.gitignore, org.ermadan.kafkalytic, org.jetbrains.action-tracker, NodeJS, com.intellij.plugins.html.instantEditing, com.jetbrains.lang.ejs, org.jetbrains.plugins.node-remote-interpreter, com.intellij.lang.puppet, training

**Comment by ermadan** [comment]
эта ошибка говорит о том что плагин не может приконнектиться к серверам указанным в конфигурации кластера

**Comment by ermadan** [comment]
fixed, uploaded fix as part of stable version 0.8, will be available for download in a day

**Comment by RustamKuramshin** [comment]
Good!

**Comment by RustamKuramshin** [comment]
Проверил, вроде работает. Спасибо за оперативность.
