### ISSUE TITLE
IndexOutOfBounds, consumptionProgress with multiple partitions

### ISSUE THREAD

**Issue by chklauser** [ermadan/kafkalytic#20]
I'm getting the following exception when I try to show consumption progress on a topic with multiple partitions. I'm not super sure, if it is really related to having multiple partitions, but I was able to monitor progress on that topic just fine until I increased the number of partitions on it from 1 to 5.

```
java.lang.IndexOutOfBoundsException: Index 2 out of bounds for length 2
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
	at java.base/java.util.Objects.checkIndex(Objects.java:372)
	at java.base/java.util.ArrayList.get(ArrayList.java:459)
	at org.kafkalytic.plugin.OffsetsTableModel.updateDetails(ProgressDialog.kt:123)
	at org.kafkalytic.plugin.ProgressDialog$update$1.run(ProgressDialog.kt:34)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:201)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$invokeLater$4(ApplicationImpl.java:322)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:84)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:132)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:47)
	at com.intellij.openapi.application.impl.FlushQueue$FlushNow.run(FlushQueue.java:188)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:971)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:841)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:452)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:744)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:451)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:802)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:499)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
```

Thanks for working on this plugin. It's been very handy so far 😄

**Comment by davidpedrosa** [comment]
Hi. Thank you very much for this plugin.

I have been looking into this issue.

The bug can be reproduced as follows:

1) Create a topic. The default partitions number which is one is ok.
2) Subscribe a consumer to the aforementioned topic. For this I have used the kafka-console-consumer from a standard kafka installation. 
If you were to open "show consumption progress" everything is all right.
3) Change the partitions number to 2 or a greater value than the topic's current.
4) Open "show consumption progress" again. Now the form is not properly populated and you can find the error in the event log.

I have created a pull request fixing the issue where I also explaing further the cause.

**Comment by ermadan** [comment]
David, i uploaded version 0.9.12 in alpha channel, it will be available for download in couple of days, i will release it in stable after testing alpha

**Comment by davidpedrosa** [comment]
Nice. If I may be of any further assistance, please, let me know.

**Comment by ermadan** [comment]
David - if you have time and ideas how to evolve plugin - you are more than welcome. Also there are few feature requests...
