### ISSUE TITLE
Wrong header syntax

### ISSUE THREAD

**Issue by IrinaKhameeva** [ermadan/kafkalytic#36]
Folder **Topics**. From the topic's dropdown context menu choose  **Publish single message**. Enter following string "uyiuytiuytiuyttiuyt", fill out **key/value** , **text** field and tap **OK** button. IDE error occurred at the right bottom corner.

java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 4
	at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
	at java.base/java.lang.String.substring(String.java:1874)
	at org.kafkalytic.plugin.KafkaUtilsKt.createCustomHeader(KafkaUtils.kt:280)
	at org.kafkalytic.plugin.KafkaUtilsKt.createCustomHeader$default(KafkaUtils.kt:272)
	at org.kafkalytic.plugin.KafkaUtilsKt.produceSingleMessage(KafkaUtils.kt:264)
	at org.kafkalytic.plugin.MainWindow$3$mousePressed$7$1.invoke(MainWindow.kt:240)
	at org.kafkalytic.plugin.MainWindow$3$mousePressed$7$1.invoke(MainWindow.kt:142)
	at org.kafkalytic.plugin.MainWindow$CancelableTask.run(MainWindow.kt:522)
	at com.intellij.openapi.progress.impl.CoreProgressManager.startTask(CoreProgressManager.java:450)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.startTask(ProgressManagerImpl.java:117)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcessWithProgressAsync$5(CoreProgressManager.java:510)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by lethuan692** [comment]
Custom header format:
**key:value** not ~~key/value~~
